import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Admin',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guides/admin/announcements', label: 'Managing announcements' },
        { type: 'doc', id: 'guides/admin/directory-management', label: 'Managing residents' },
      ],
    },
    {
      type: 'category',
      label: 'Residents',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guides/resident/announcements', label: 'Official announcements' },
        { type: 'doc', id: 'guides/resident/neighbours', label: 'Neighbor directory' },
      ],
    },
  ],
  developersSidebar: [
    {
      type: 'category',
      label: 'Announcements',
      items: [{ type: 'autogenerated', dirName: 'developers/announcements' }],
    },
    {
      type: 'category',
      label: 'Neighbor Directory',
      items: [{ type: 'autogenerated', dirName: 'developers/residents' }],
    },
  ],
};

export default sidebars;
