import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  developersSidebar: [{ type: 'autogenerated', dirName: 'developers' }],
  featuresSidebar: [{ type: 'autogenerated', dirName: 'features' }],
  supportSidebar: [{ type: 'autogenerated', dirName: 'support' }],
};

export default sidebars;
